apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.metadata.name }}
  namespace: {{ .Values.volumes.metadata.namespace }}
  labels:
    {{- range $key, $value := .Values.volumes.metadata.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  storageClassName: {{ .Values.volumes.spec.storageClassName }}
  accessModes:
    {{- range .Values.volumes.spec.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.spec.resources.requests.storage }}