apiVersion: v1
kind: Service
metadata:
  name: {{ include "giropopsSenhas.fullname" . }}
  labels:
    {{- include "giropopsSenhas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}  # Use default value if not provided
  selector:
    {{- toYaml .Values.service.selector | nindent 4 }}  # Ensure the selector is properly rendered
  ports:
    - name: http
      port: {{ .Values.service.port | default 5000 }}  # Use default value if not provided
      targetPort: {{ .Values.service.targetPort | default 5000 }}  # Use default value if not provided
