{{- if and .Values.persistence.enabled .Values.persistence.create }}

{{- range .Values.persistence.claims }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .name }}
  labels: {{ include "rundeck.labels" $ | indent 4 }}
  annotations:
  {{- if .storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .storageClass | quote }}
  {{- end }}
spec:
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
---
{{- end }}
{{- end }}
