name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "nataliagranato"
          git config user.email "nataliagranato@ufmg.br"

      - name: Update Dependencies
        run: |
          cd charts/trudesk
          helm dependency update

      - name: Add Helm Repositories
        run: |
          helm repo add elastic https://helm.elastic.co
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.USER_TOKEN }}"
